version: '3.8'

services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: coffee_db
    restart: always
    environment:
      - POSTGRES_USER=coffee_user
      - POSTGRES_PASSWORD=coffee_pw
      - POSTGRES_DB=coffee_tracker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de la API
  api:
    build: .
    container_name: coffee_api
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    environment:
      # IMPORTANTE: Aquí usamos 'db' en lugar de 'localhost' 
      # porque en Docker los servicios se hablan por su nombre.
      - DATABASE_URL=postgresql+psycopg://coffee_user:coffee_pw@db:5432/coffee_tracker
      - DEBUG=True
    depends_on:
      - db

volumes:
  postgres_data: